spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kbhealth
    username: root
    password: RootRoot1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  api:
    food:
      service-key: "BcbiMs4jqpSBNZDnJX7zIB9Jv1hsF3z7tV5SixMjUlkMba0eUIDr4Gd5pxRaNQKbLoDiyVf26xUWtWghhLA2BQ%3D%3D"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  secret: "snyyDePsHkl0X/ZrKIOLCo+GWuGK4HdhaDNESHufeUU="
openai:
  api-key: ""
  model: "gpt-4-turbo"
  url: "https://api.openai.com/v1/chat/completions"
