spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kbhealth
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  api:
    food:
      service-key: "BcbiMs4jqpSBNZDnJX7zIB9Jv1hsF3z7tV5SixMjUlkMba0eUIDr4Gd5pxRaNQKbLoDiyVf26xUWtWghhLA2BQ%3D%3D"
jwt:
  secret: "snyyDePsHkl0X/ZrKIOLCo+GWuGK4HdhaDNESHufeUU="
openai:
  api-key: ""
  model: "gpt-4-turbo"
  url: "https://api.openai.com/v1/chat/completions"
